In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('/content/drive/MyDrive/MachineL/NLP/IMDB Dataset.csv')
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df["review"][0].lower()

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.<br /><br />the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.<br /><br />it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

### Lowercasing

In [5]:
df["review"] = df["review"].str.lower()

In [6]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

### Remove HTML tags

In [7]:
import re
def remove_tags(tetx):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', tetx)

In [8]:
df["review"].apply(remove_tags)

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

### Remove URLS

In [9]:
#function to remove urls
def remove_urls(text):
    url = re.compile(r'https?://\S+|www\.\S+')
    return url.sub(r'', text)

### Removing punctuation

In [10]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [11]:
exclude = string.punctuation

In [12]:
def remove_punc(text):
    return text.translate(str.maketrans('', '', exclude))

### Chat word treatment

## short message words

### Spelling Correction

In [13]:
from textblob import TextBlob

In [14]:
incorrect_text = "I havv goood speling"
corrected_text = TextBlob(incorrect_text).correct() 
print(corrected_text)

I have good spelling

### Stopwords

In [7]:
%pip install nltk

Collecting nltk
  Downloading nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: click in e:\deepfake_envs\deepfake\lib\site-packages (from nltk) (8.3.2)
Requirement already satisfied: joblib in e:\deepfake_envs\deepfake\lib\site-packages (from nltk) (1.5.3)
Collecting regex>=2021.8.3 (from nltk)
  Using cached regex-2026.5.9-cp310-cp310-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Downloading tqdm-4.68.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in e:\deepfake_envs\deepfake\lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.4-py3-none-any.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   -------------------- ------------------- 0.8/1.6 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 6.4 MB/s  0:00:00
Using cached regex-2026.5.9-cp310-cp310-win_amd64.whl (278 kB)
Downloading tqdm-4.68.1-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, regex, nltk

   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   ---------------------------------------- 3/3 [nltk]

Successfully installed nltk-3.9.4 regex-2026.5.9 tqdm-4.68.1
Note: you may need to restart the kernel to use updated packages.

In [8]:
import nltk

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\chand\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [16]:
from nltk.corpus import stopwords

In [17]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [18]:
def remove_stopwords(text):
    new_txt=[]

    for word in text.split():
        if word not in stopwords.words('english'):
            new_txt.append(word)
    return ' '.join(new_txt)

In [19]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [20]:
df["review"]=df["review"].apply(remove_stopwords)

In [21]:
#to remove emojis
import re
def remove_emjo(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [25]:
!pip install emoji

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 16.9 MB/s eta 0:00:0000:01
Installing collected packages: emoji
Successfully installed emoji-2.15.0

In [26]:
#to replace emoji with text
import emoji

### Tokenization

In [1]:
#using the split function
#word tokenization
sen1="I am goning to delhi"
sen1.split()

['I', 'am', 'goning', 'to', 'delhi']

In [2]:
#sentence Tokenization
sen1="I am goning to delhi. I will be there for 2 days."
SEN1=sen1.split('.')
SEN1

['I am goning to delhi', ' I will be there for 2 days', '']

### NLTK

In [9]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\chand\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\chand\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [15]:
from nltk.tokenize import word_tokenize

In [18]:
sen1="I am goning to delhi!"
word_tokenize(sen1)

['I', 'am', 'goning', 'to', 'delhi', '!']

In [17]:
text="I am goning to delhi. I will be there for 2 days."
sentences = nltk.sent_tokenize(text)
sentences

['I am goning to delhi.', 'I will be there for 2 days.']

### Spacy library

### Stemming

In [19]:
#stemming from nltk 
text="walking walked walks"
from nltk.stem import PorterStemmer
ps = PorterStemmer()
for word in text.split():
    print(ps.stem(word))

walk
walk
walk

In [ ]:
#lemmatizaton
from nltk.stem import WordNetLemmatizer 
lemmatizer = WordNetLemmatizer()

### Bag of words

In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.DataFrame({"text":["people watch campusx","campusx watch campusx","people write comment","campusx write comment"],"output":[0,0,1,1]})

In [4]:
df

                    text  output
0   people watch campusx       0
1  campusx watch campusx       0
2   people write comment       1
3  campusx write comment       1

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [6]:
bow=cv.fit_transform(df["text"])

In [7]:
#vocabulary
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [8]:
print(bow.toarray())

[[1 0 1 1 0]
 [2 0 0 1 0]
 [0 1 1 0 1]
 [1 1 0 0 1]]

In [9]:
#for new text
cv.transform(["people watch physics"]).toarray()

array([[0, 0, 1, 1, 0]])

### Ngram

In [12]:
#bigram 
cv2=CountVectorizer(ngram_range=(2,2))
cv2.fit_transform(df["text"]).toarray()

array([[0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1]])

In [13]:
print(cv2.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}

### TFIDF

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()

In [15]:
tfidf.fit_transform(df["text"]).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [17]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['campusx' 'comment' 'people' 'watch' 'write']

### Word2Vec Pre-trained

In [11]:
%pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp310-cp310-win_amd64.whl.metadata (8.6 kB)
Requirement already satisfied: numpy>=1.18.5 in e:\deepfake_envs\deepfake\lib\site-packages (from gensim) (1.23.5)
Requirement already satisfied: scipy>=1.7.0 in e:\deepfake_envs\deepfake\lib\site-packages (from gensim) (1.15.2)
Collecting smart_open>=1.8.1 (from gensim)
  Downloading smart_open-7.6.1-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: wrapt in e:\deepfake_envs\deepfake\lib\site-packages (from smart_open>=1.8.1->gensim) (2.1.2)
Downloading gensim-4.4.0-cp310-cp310-win_amd64.whl (24.4 MB)
   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/24.4 MB ? eta -:--:--
   - -------------------------------------- 1.0/24.4 MB 4.6 MB/s eta 0:00:06
   --- ------------------------------------ 2.1/24.4 MB 4.7 MB/s eta 0:00:05
   ----- ---------------------------------- 3.4/24.4 MB 5.2 MB/s eta 0:00:05
   -------- ------------------------------- 5.0/24.4 MB 5.7 MB/s eta 0:00:04
   ----------- ---------------------------- 6.8/24.4 MB 6.3 MB/s eta 0:00:03
   -------------- ------------------------- 8.9/24.4 MB 6.8 MB/s eta 0:00:03
   ------------------ --------------------- 11.3/24.4 MB 7.4 MB/s eta 0:00:02
   ---------------------- ----------------- 13.9/24.4 MB 8.1 MB/s eta 0:00:02
   --------------------------- ------------ 16.8/24.4 MB 8.7 MB/s eta 0:00:01
   --------------------------------- ------ 20.2/24.4 MB 9.4 MB/s eta 0:00:01
   ---------------------------------------  24.1/24.4 MB 10.2 MB/s eta 0:00:01
   ---------------------------------------- 24.4/24.4 MB 10.2 MB/s  0:00:02
Downloading smart_open-7.6.1-py3-none-any.whl (64 kB)
Installing collected packages: smart_open, gensim

   -------------------- ------------------- 1/2 [gensim]
   -------------------- ------------------- 1/2 [gensim]
   -------------------- ------------------- 1/2 [gensim]
   -------------------- ------------------- 1/2 [gensim]
   ---------------------------------------- 2/2 [gensim]

Successfully installed gensim-4.4.0 smart_open-7.6.1
Note: you may need to restart the kernel to use updated packages.

In [12]:
import gensim
from gensim.models import Word2Vec,keyedvectors

In [2]:
import os

In [13]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [17]:
import os

story = []

folder_path = r"C:\Users\chand\Downloads\GOT"

for filename in os.listdir(folder_path):
    file_path = os.path.join(folder_path, filename)

    with open(file_path, "r", encoding="latin-1") as f:
        corpus = f.read()

    raw_sent = sent_tokenize(corpus)

    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [18]:
len(story)

145020

In [20]:
from gensim.parsing.preprocessing import STOPWORDS

story = [
    [word for word in sent if word not in STOPWORDS and len(word) > 2]
    for sent in story
]

In [21]:
story[0]

['game',
 'thrones',
 'book',
 'song',
 'ice',
 'george',
 'martin',
 'prologue',
 'start',
 'gared',
 'urged',
 'woods',
 'began',
 'grow',
 'dark']

In [22]:
model = gensim.models.Word2Vec(
    window=5,
    min_count=2,
    workers=4,
)

In [23]:
model.build_vocab(story)

In [24]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(3838318, 3988935)

In [26]:
model.wv.most_similar("daenerys")

[('stormborn', 0.9534960389137268),
 ('unburnt', 0.9084994196891785),
 ('share', 0.8830752968788147),
 ('margaery', 0.8792731165885925),
 ('elia', 0.8759588599205017),
 ('course', 0.8757070899009705),
 ('noble', 0.8755025863647461),
 ('court', 0.8751880526542664),
 ('princess', 0.8743407130241394),
 ('promise', 0.8716152906417847)]

In [27]:
model.wv.doesnt_match(["daenerys", "jon", "tyrion", "winterfell"])

'tyrion'

In [28]:
model.wv.most_similar("king")

[('baratheon', 0.7831211686134338),
 ('site', 0.7362107038497925),
 ('prince', 0.7149165868759155),
 ('fawning', 0.7083502411842346),
 ('tourney', 0.6974592208862305),
 ('royal', 0.6865183115005493),
 ('rhaegar', 0.680010199546814),
 ('targaryen', 0.6794591546058655),
 ('aegon', 0.6773200631141663),
 ('mng', 0.6772168278694153)]

In [30]:
model.wv.doesnt_match(["jon","sansa","arya","bran","robb","rikon"])

'jon'

In [31]:
model.wv["daenerys"]

array([-0.1820841 ,  0.35313532,  0.43265104,  0.44460687,  0.23817743,
       -0.6275334 , -0.13537581,  0.7342594 , -0.4201148 , -0.1916245 ,
       -0.57870865, -0.35938075, -0.44619963,  1.0578843 ,  0.00749689,
       -0.57812095, -0.6443775 , -0.3198661 , -0.14429896, -1.133078  ,
        0.77126974,  0.07048631,  0.04564338,  0.26253375,  0.02283351,
       -0.01885047, -0.26074684, -0.18850197, -0.6936526 , -0.24100025,
       -0.3024245 ,  0.42003652, -0.3950231 ,  0.1589591 ,  0.0859921 ,
        1.1535581 , -0.01903228, -0.40286154,  0.09353198, -0.7489846 ,
       -0.5805602 ,  0.09329786, -0.14148845,  0.81217086,  0.08905794,
       -0.35326967,  0.15089016,  0.53204274,  0.49025306,  0.40609437,
        0.1766899 , -0.34937033,  0.32926536,  0.4688091 , -0.00262688,
       -0.09361347, -0.27571484,  0.4721411 , -0.630534  ,  0.19136149,
        0.27429178,  0.10046571, -0.35238403, -0.5583461 , -0.5841736 ,
        0.1395674 ,  0.22152211,  0.9636909 ,  0.27195233,  0.52605397,
       -0.4939414 ,  0.2438915 ,  0.06507919, -0.20282985,  0.5668433 ,
        0.05184217,  0.42166588, -0.01705712, -0.13415697, -0.6919752 ,
        0.01472589,  0.37566563, -0.60980546,  0.31134775, -0.01627387,
        0.39037806,  0.06515095,  0.81296825,  0.2029796 ,  0.7567907 ,
        0.8842118 ,  0.1351311 , -0.29828444, -0.25551313,  0.55580276,
        1.015707  , -0.12008323, -0.13520369,  0.00136468,  0.03391669],
      dtype=float32)

In [32]:
model.wv.similarity("daenerys","jon")

0.103925616

In [33]:
model.wv.get_normed_vectors()

array([[-0.11720707,  0.04813647,  0.13139871, ..., -0.05263452,
         0.02216483,  0.11105505],
       [-0.09143785,  0.06324168,  0.15992945, ...,  0.02130175,
        -0.06054636,  0.12753038],
       [-0.00504507,  0.12321634,  0.00145595, ...,  0.04379991,
         0.10402881,  0.03943897],
       ...,
       [-0.00135795,  0.10246798,  0.05219249, ..., -0.18359962,
        -0.03286178,  0.02032802],
       [ 0.02068603,  0.17278133,  0.093455  , ..., -0.21119192,
         0.05187791, -0.00096507],
       [-0.12336123,  0.09286921, -0.00721075, ...,  0.05424579,
        -0.02732448,  0.03358142]], dtype=float32)

In [34]:
y=model.wv.index_to_key

In [35]:
y

['said',
 'lord',
 'ser',
 'man',
 'king',
 'men',
 'like',
 'jon',
 'father',
 'old',
 'hand',
 'tyrion',
 'know',
 'eyes',
 'black',
 'told',
 'lady',
 'thought',
 'time',
 'long',
 'come',
 'face',
 'head',
 'red',
 'way',
 'boy',
 'page',
 'queen',
 'good',
 'brother',
 'night',
 'little',
 'took',
 'came',
 'away',
 'dead',
 'son',
 'blood',
 'half',
 'arya',
 'saw',
 'day',
 'white',
 'jaime',
 'look',
 'want',
 'sword',
 'tell',
 'girl',
 'bran',
 'great',
 'looked',
 'left',
 'knew',
 'asked',
 'gave',
 'maester',
 'called',
 'wall',
 'heard',
 'sansa',
 'let',
 'went',
 'turned',
 'dany',
 'need',
 'woman',
 'snow',
 'beneath',
 'knight',
 'grace',
 'gold',
 'cersei',
 'castle',
 'stark',
 'gods',
 'think',
 'hair',
 'feet',
 'hands',
 'stannis',
 'mother',
 'catelyn',
 'robert',
 'prince',
 'robb',
 'lannister',
 'hear',
 'grey',
 'horse',
 'high',
 'stone',
 'wine',
 'hard',
 'water',
 'iron',
 'voice',
 'gone',
 'sam',
 'better',
 'seen',
 'shall',
 'ned',
 'years',
 'dark',
 'place',
 'small',
 'cold',
 'winterfell',
 'stood',
 'end',
 'sister',
 'words',
 'sea',
 'right',
 'walls',
 'fingers',
 'house',
 'cloak',
 'young',
 'seven',
 'mouth',
 'watch',
 'door',
 'joffrey',
 'green',
 'big',
 'sent',
 'wanted',
 'daughter',
 'true',
 'leave',
 'city',
 'wind',
 'light',
 'arms',
 'children',
 'sweet',
 'lost',
 'theon',
 'felt',
 'yes',
 'brothers',
 'best',
 'die',
 'brought',
 'soon',
 'died',
 'far',
 'north',
 'child',
 'fear',
 'brienne',
 'word',
 'taken',
 'battle',
 'help',
 'new',
 'tywin',
 'davos',
 'lords',
 'mean',
 'wife',
 'hall',
 'rest',
 'kill',
 'strong',
 'steel',
 'began',
 'won',
 'sound',
 'dragon',
 'past',
 'life',
 'tower',
 'killed',
 'arm',
 'tried',
 'sons',
 'free',
 'thing',
 'bear',
 'days',
 'bloody',
 'heart',
 'pale',
 'love',
 'moment',
 'sat',
 'bring',
 'bed',
 'close',
 'knights',
 'cut',
 'wolf',
 'death',
 'horses',
 'smile',
 'inside',
 'brown',
 'dragons',
 'hot',
 'silver',
 'bastard',
 'open',
 'thousand',
 'landing',
 'uncle',
 'going',
 'blue',
 'captain',
 'air',
 'laughed',
 'river',
 'sun',
 'rose',
 'fell',
 'war',
 'golden',
 'sleep',
 'swords',
 'renly',
 'speak',
 'certain',
 'fool',
 'feel',
 'send',
 'tongue',
 'fight',
 'got',
 'set',
 'rode',
 'world',
 'throat',
 'legs',
 'deep',
 'honor',
 'rock',
 'trees',
 'tall',
 'table',
 'pulled',
 'broken',
 'women',
 'mormont',
 'steps',
 'things',
 'hodor',
 'heavy',
 'burned',
 'skin',
 'given',
 'dwarf',
 'moved',
 'smiled',
 'storm',
 'raised',
 'ask',
 'ride',
 'eye',
 'hope',
 'reached',
 'soft',
 'frey',
 'second',
 'remember',
 'remembered',
 'coming',
 'meant',
 'hold',
 'morning',
 'teeth',
 'throne',
 'command',
 'fat',
 'truth',
 'walder',
 'commander',
 'doubt',
 'ground',
 'jorah',
 'cup',
 'outside',
 'known',
 'wore',
 'ran',
 'gate',
 'room',
 'held',
 'closed',
 'home',
 'matter',
 'south',
 'wood',
 'sky',
 'wed',
 'people',
 'dozen',
 'neck',
 'food',
 'riverrun',
 'instead',
 'near',
 'turn',
 'talk',
 'ships',
 'tyrell',
 'moon',
 'bolton',
 'lips',
 'summer',
 'shadow',
 'watched',
 'times',
 'leather',
 'varys',
 'shoulder',
 'septon',
 'warm',
 'caught',
 'believe',
 'guards',
 'answer',
 'god',
 'blade',
 'wondered',
 'ice',
 'barristan',
 'shield',
 'opened',
 'armor',
 'safe',
 'kept',
 'return',
 'wish',
 'tommen',
 'smell',
 'foot',
 'squire',
 'floor',
 'eddard',
 'run',
 'followed',
 'serve',
 'friends',
 'boys',
 'beard',
 'wedding',
 'cloaks',
 'baratheon',
 'eat',
 'wrong',
 'daenerys',
 'ghost',
 'sight',
 'hound',
 'flesh',
 'ship',
 'strength',
 'nose',
 'returned',
 'bones',
 'crown',
 'yellow',
 'chest',
 'covered',
 'commanded',
 'says',
 'petyr',
 'filled',
 'aemon',
 'led',
 'friend',
 'aye',
 'common',
 'flames',
 'fighting',
 'spoke',
 'asha',
 'aside',
 'lysa',
 'huge',
 'crow',
 'belly',
 'master',
 'breath',
 'yard',
 'gates',
 'waiting',
 'looking',
 'wooden',
 'wet',
 'realm',
 'work',
 'bad',
 'promised',
 'use',
 'husband',
 'grew',
 'tree',
 'later',
 'loved',
 'wildlings',
 'girls',
 'greyjoy',
 'afraid',
 'rain',
 'shoulders',
 'walked',
 'shouted',
 'maid',
 'remained',
 'mance',
 'late',
 'guard',
 'meereen',
 'littlefinger',
 'liked',
 'fall',
 'margaery',
 'dog',
 'year',
 'hurt',
 'passed',
 'balon',
 'taste',
 'dothraki',
 'drew',
 'lay',
 'spear',
 'realized',
 'pushed',
 'song',
 'named',
 'sure',
 'stand',
 'reach',
 'brave',
 'finally',
 'whispered',
 'different',
 'wolves',
 'suddenly',
 'poor',
 'kingsguard',
 'drogo',
 'stay',
 'arryn',
 'stop',
 'kingdoms',
 'edmure',
 'broke',
 'ears',
 'princess',
 'burning',
 'faces',
 'lannisters',
 'dream',
 'direwolf',
 'axe',
 'west',
 'heir',
 'tears',
 'drink',
 'clegane',
 'darkness',
 'raven',
 'pointed',
 'hill',
 'try',
 'forward',
 'pain',
 'sworn',
 'khal',
 'lie',
 'dagger',
 'truly',
 'kings',
 'seat',
 'grown',
 'road',
 'born',
 'harrenhal',
 'care',
 'bronn',
 'helm',
 'round',
 'feast',
 'meat',
 'pycelle',
 'quick',
 'understand',
 'longer',
 'lifted',
 'whilst',
 'reminded',
 'maybe',
 'mountain',
 'short',
 'step',
 'rodrik',
 'melisandre',
 'ones',
 'pretty',
 'aegon',
 'lands',
 'bit',
 'stopped',
 'worse',
 'sit',
 'victarion',
 'save',
 'sharp',
 'knows',
 'live',
 'smoke',
 'horn',
 'leg',
 'window',
 'pray',
 'younger',
 'westeros',
 'silk',
 'heads',
 'pie',
 'septa',
 'peace',
 'slaves',
 'ago',
 'hizdahr',
 'wants',
 'bread',
 'mind',
 'low',
 'laugh',
 'east',
 'blind',
 'reek',
 'towers',
 'mad',
 'bright',
 'sooner',
 'slain',
 'coin',
 'making',
 'camp',
 'older',
 'salt',
 'drowned',
 'served',
 'wait',
 'narrow',
 'walk',
 'point',
 'glanced',
 'cousin',
 'cheeks',
 'luwin',
 'knife',
 'stepped',
 'shook',
 'quiet',
 'sort',
 'targaryen',
 'touched',
 'riding',
 'loras',
 'naked',
 'twisted',
 'choice',
 'kevan',
 'fish',
 'lion',
 'forgotten',
 'silence',
 'ramsay',
 'hung',
 'read',
 'gift',
 'running',
 'fallen',
 'replied',
 'large',
 'knees',
 'fought',
 'silent',
 'cat',
 'company',
 'ahead',
 'beautiful',
 'rhaegar',
 'needs',
 'dawn',
 'sept',
 'dogs',
 'pass',
 'dorne',
 'casterly',
 'knee',
 'tully',
 'mud',
 'gregor',
 'stupid',
 'singer',
 'court',
 'body',
 'meera',
 'age',
 'trying',
 'swear',
 'kind',
 'gendry',
 'offered',
 'clothes',
 'leaves',
 'closer',
 'kiss',
 'wonder',
 'pay',
 'agreed',
 'threw',
 'answered',
 'climbed',
 'saying',
 'wide',
 'saddle',
 'stars',
 'comes',
 'chain',
 'trust',
 'host',
 'stones',
 'pleased',
 'trident',
 'fair',
 'yunkai',
 'spears',
 'hour',
 'dry',
 'dying',
 'ear',
 'insisted',
 'fast',
 'carried',
 'service',
 'doors',
 'ought',
 'mail',
 'fist',
 'council',
 'woods',
 'thank',
 'crossed',
 'join',
 'needed',
 'milk',
 'wasn',
 'fine',
 'wildling',
 'quentyn',
 'gilly',
 'finger',
 'tent',
 'shadows',
 'win',
 'helped',
 'land',
 'bird',
 'boots',
 'folk',
 'crows',
 'imp',
 'names',
 'kissed',
 'letter',
 'banners',
 'winter',
 'pink',
 'screamed',
 'angry',
 'frightened',
 'torch',
 'learn',
 'alive',
 'chair',
 'eunuch',
 'daughters',
 'watching',
 'tarly',
 'harm',
 'dragonstone',
 'fires',
 'serving',
 'standing',
 'easy',
 'learned',
 'wings',
 'drunk',
 'question',
 'myrcella',
 'priest',
 'sail',
 'sisters',
 'nodded',
 'harbor',
 'bone',
 'giant',
 'forth',
 'warned',
 'field',
 'slow',
 'slipped',
 'slid',
 'dreams',
 'bronze',
 'slowly',
 'falling',
 'promise',
 'atop',
 'whore',
 'slave',
 'illyrio',
 'line',
 'rise',
 'pyke',
 'makes',
 'flowers',
 'laughter',
 'grass',
 'faced',
 'declared',
 'bay',
 'earth',
 'loose',
 'power',
 'viserys',
 'lived',
 'twice',
 'cell',
 'happened',
 'play',
 'chains',
 'oldtown',
 'break',
 'dance',
 'clean',
 'aerys',
 'surely',
 'claim',
 'jeyne',
 'eyrie',
 'fresh',
 'cried',
 'tormund',
 'craster',
 'pair',
 'laid',
 'shouting',
 'morrow',
 'sad',
 'met',
 'game',
 'rule',
 'touch',
 'softly',
 'steward',
 'woke',
 'count',
 'started',
 'mounted',
 'afterward',
 'sense',
 'jojen',
 'captive',
 'highgarden',
 'hide',
 'waters',
 'sudden',
 'ravens',
 'cheek',
 'taking',
 'course',
 'follow',
 'purple',
 'means',
 'wench',
 'noble',
 'carved',
 'rickon',
 'bare',
 'grenn',
 'waited',
 'rising',
 'murdered',
 'vale',
 'thinking',
 'weak',
 'cruel',
 'roose',
 'roof',
 'wouldn',
 'hidden',
 'eyed',
 'arrow',
 'town',
 'blow',
 'forest',
 'wise',
 'grand',
 'hungry',
 'growing',
 'voices',
 'today',
 'army',
 'sorry',
 'griff',
 'tale',
 'wound',
 'protect',
 'beric',
 'inn',
 'twins',
 'weight',
 'ugly',
 'ygritte',
 'sick',
 'hoped',
 'forget',
 'rolled',
 'dressed',
 'knelt',
 'climb',
 'enemies',
 'daario',
 'chance',
 'marry',
 'fur',
 'courage',
 'lad',
 'grow',
 'freys',
 'fleet',
 'smiling',
 'laughing',
 'bride',
 'corpse',
 'marriage',
 'unsullied',
 'appeared',
 'breasts',
 'meet',
 'square',
 'showed',
 'kingslayer',
 'drank',
 'wool',
 'alayne',
 'march',
 'mountains',
 'mercy',
 'frozen',
 'trouble',
 'edge',
 'shae',
 'slynt',
 'arrows',
 'wear',
 'ragged',
 'decided',
 'offer',
 'welcome',
 'allowed',
 'swore',
 'recall',
 'bound',
 'sing',
 'ill',
 'spread',
 'mace',
 'slept',
 'seated',
 'quickly',
 'wake',
 'sounded',
 'tales',
 'moving',
 'ancient',
 'flew',
 'talking',
 'dare',
 'bowed',
 'sellsword',
 'yoren',
 'till',
 'apart',
 'paid',
 'longsword',
 'lead',
 'living',
 'penny',
 'breast',
 'duty',
 'claimed',
 'riders',
 'orange',
 'ate',
 'joff',
 'royal',
 'carry',
 'beat',
 'grabbed',
 'reznak',
 'babe',
 'sellswords',
 'lives',
 'rivers',
 'euron',
 'captains',
 'village',
 'defend',
 'ale',
 'blackwater',
 'dreamed',
 'tight',
 'leaving',
 'remain',
 'ben',
 'sighed',
 'beast',
 'listen',
 'shrugged',
 'wild',
 'sand',
 'whores',
 'leaned',
 'braavos',
 'servants',
 'stared',
 'joined',
 'lancel',
 'lot',
 'clever',
 'maiden',
 'redwyne',
 'cause',
 'godswood',
 'bridge',
 'banner',
 'handed',
 'astapor',
 'supper',
 'bedchamber',
 'able',
 'looks',
 'strange',
 'cracked',
 'shore',
 'parchment',
 'bow',
 'feared',
 'beg',
 'tonight',
 'tom',
 'deck',
 'fit',
 'lordship',
 'nights',
 'sandor',
 'entered',
 'fled',
 'streets',
 'grief',
 'smelled',
 'hills',
 'swung',
 'widow',
 'thousands',
 'commands',
 'queer',
 'starks',
 'arianne',
 'marsh',
 'khaleesi',
 'announced',
 'chambers',
 'bannermen',
 'qyburn',
 'leagues',
 'scarcely',
 'pleasure',
 'terrible',
 'nan',
 'warrior',
 'candle',
 'frowned',
 'valyrian',
 'plain',
 'janos',
 'breeches',
 'shoved',
 ...]

In [36]:
from sklearn.decomposition import PCA

In [43]:
pca=PCA(n_components=3)

In [44]:
X= pca.fit_transform(model.wv.get_normed_vectors())

In [45]:
X.shape

(17103, 3)

### POS

In [46]:
%pip install spaCy

Collecting spaCy
  Downloading spacy-3.8.14-cp310-cp310-win_amd64.whl.metadata (28 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spaCy)
  Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spaCy)
  Downloading spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spaCy)
  Downloading murmurhash-1.0.15-cp310-cp310-win_amd64.whl.metadata (2.3 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spaCy)
  Downloading cymem-2.0.13-cp310-cp310-win_amd64.whl.metadata (9.9 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spaCy)
  Downloading preshed-3.0.13-cp310-cp310-win_amd64.whl.metadata (5.4 kB)
Collecting thinc<8.4.0,>=8.3.12 (from spaCy)
  Downloading thinc-8.3.13-cp310-cp310-win_amd64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spaCy)
  Downloading wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.5.3 (from spaCy)
  Downloading srsly-2.5.3-cp310-cp310-win_amd64.whl.metadata (20 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spaCy)
  Downloading catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<2.0.0,>=1.0.0 (from spaCy)
  Downloading weasel-1.0.0-py3-none-any.whl.metadata (4.6 kB)
Collecting confection<2.0.0,>=1.3.2 (from spaCy)
  Downloading confection-1.3.3-py3-none-any.whl.metadata (19 kB)
Collecting typer<1.0.0,>=0.3.0 (from spaCy)
  Downloading typer-0.26.7-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in e:\deepfake_envs\deepfake\lib\site-packages (from spaCy) (4.68.1)
Requirement already satisfied: numpy>=1.19.0 in e:\deepfake_envs\deepfake\lib\site-packages (from spaCy) (1.23.5)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in e:\deepfake_envs\deepfake\lib\site-packages (from spaCy) (2.33.1)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in e:\deepfake_envs\deepfake\lib\site-packages (from spaCy) (2.12.5)
Requirement already satisfied: jinja2 in e:\deepfake_envs\deepfake\lib\site-packages (from spaCy) (3.1.6)
Requirement already satisfied: setuptools in e:\deepfake_envs\deepfake\lib\site-packages (from spaCy) (82.0.1)
Requirement already satisfied: packaging>=20.0 in e:\deepfake_envs\deepfake\lib\site-packages (from spaCy) (26.0)
Requirement already satisfied: typing_extensions<5.0,>=4.0 in e:\deepfake_envs\deepfake\lib\site-packages (from confection<2.0.0,>=1.3.2->spaCy) (4.15.0)
Requirement already satisfied: annotated-types>=0.6.0 in e:\deepfake_envs\deepfake\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spaCy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in e:\deepfake_envs\deepfake\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spaCy) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in e:\deepfake_envs\deepfake\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spaCy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in e:\deepfake_envs\deepfake\lib\site-packages (from requests<3.0.0,>=2.13.0->spaCy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in e:\deepfake_envs\deepfake\lib\site-packages (from requests<3.0.0,>=2.13.0->spaCy) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in e:\deepfake_envs\deepfake\lib\site-packages (from requests<3.0.0,>=2.13.0->spaCy) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in e:\deepfake_envs\deepfake\lib\site-packages (from requests<3.0.0,>=2.13.0->spaCy) (2026.2.25)
Collecting blis<1.4.0,>=1.3.0 (from thinc<8.4.0,>=8.3.12->spaCy)
  Downloading blis-1.3.3-cp310-cp310-win_amd64.whl.metadata (7.7 kB)
Requirement already satisfied: colorama in e:\deepfake_envs\deepfake\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spaCy) (0.4.6)
Collecting shellingham>=1.3.0 (from typer<1.0.0,>=0.3.0->spaCy)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: rich>=13.8.0 in e:\deepfake_envs\deepfake\lib\site-packages (from typer<1.0.0,>=0.3.0->spaCy) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in e:\deepfake_envs\deepfake\lib\site-packages (from typer<1.0.0,>=0.3.0->spaCy) (0.0.4)
Collecting cloudpathlib>=0.7.0 (from weasel<2.0.0,>=1.0.0->spaCy)
  Downloading cloudpathlib-0.24.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: smart-open>=5.2.1 in e:\deepfake_envs\deepfake\lib\site-packages (from weasel<2.0.0,>=1.0.0->spaCy) (7.6.1)
Collecting httpx>=0.24.0 (from weasel<2.0.0,>=1.0.0->spaCy)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: anyio in e:\deepfake_envs\deepfake\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spaCy) (4.13.0)
Collecting httpcore==1.* (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spaCy)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: h11>=0.16 in e:\deepfake_envs\deepfake\lib\site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spaCy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in e:\deepfake_envs\deepfake\lib\site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spaCy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in e:\deepfake_envs\deepfake\lib\site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spaCy) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in e:\deepfake_envs\deepfake\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spaCy) (0.1.2)
Requirement already satisfied: wrapt in e:\deepfake_envs\deepfake\lib\site-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spaCy) (2.1.2)
Requirement already satisfied: exceptiongroup>=1.0.2 in e:\deepfake_envs\deepfake\lib\site-packages (from anyio->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spaCy) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in e:\deepfake_envs\deepfake\lib\site-packages (from jinja2->spaCy) (3.0.3)
Downloading spacy-3.8.14-cp310-cp310-win_amd64.whl (15.4 MB)
   ---------------------------------------- 0.0/15.4 MB ? eta -:--:--
    --------------------------------------- 0.3/15.4 MB ? eta -:--:--
   -- ------------------------------------- 0.8/15.4 MB 2.2 MB/s eta 0:00:07
   --- ------------------------------------ 1.3/15.4 MB 2.4 MB/s eta 0:00:06
   ---- ----------------------------------- 1.8/15.4 MB 2.6 MB/s eta 0:00:06
   ------ --------------------------------- 2.6/15.4 MB 2.7 MB/s eta 0:00:05
   -------- ------------------------------- 3.1/15.4 MB 2.8 MB/s eta 0:00:05
   ---------- ----------------------------- 4.2/15.4 MB 3.1 MB/s eta 0:00:04
   ------------- -------------------------- 5.2/15.4 MB 3.4 MB/s eta 0:00:03
   ----------------- ---------------------- 6.8/15.4 MB 3.8 MB/s eta 0:00:03
   --------------------- ------------------ 8.4/15.4 MB 4.3 MB/s eta 0:00:02
   -------------------------- ------------- 10.2/15.4 MB 4.7 MB/s eta 0:00:02
   -------------------------------- ------- 12.3/15.4 MB 5.2 MB/s eta 0:00:01
   -------------------------------------- - 14.7/15.4 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------- 15.4/15.4 MB 5.8 MB/s  0:00:02
Downloading catalogue-2.0.10-py3-none-any.whl (17 kB)
Downloading confection-1.3.3-py3-none-any.whl (35 kB)
Downloading cymem-2.0.13-cp310-cp310-win_amd64.whl (40 kB)
Downloading murmurhash-1.0.15-cp310-cp310-win_amd64.whl (25 kB)
Downloading preshed-3.0.13-cp310-cp310-win_amd64.whl (121 kB)
Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Downloading spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Downloading srsly-2.5.3-cp310-cp310-win_amd64.whl (651 kB)
   ---------------------------------------- 0.0/651.7 kB ? eta -:--:--
   ---------------------------------------- 651.7/651.7 kB 8.3 MB/s  0:00:00
Downloading thinc-8.3.13-cp310-cp310-win_amd64.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 1.8/1.8 MB 14.1 MB/s  0:00:00
Downloading blis-1.3.3-cp310-cp310-win_amd64.whl (6.2 MB)
   ---------------------------------------- 0.0/6.2 MB ? eta -:--:--
   -------------------- ------------------- 3.1/6.2 MB 15.3 MB/s eta 0:00:01
   ---------------------------------------- 6.2/6.2 MB 14.6 MB/s  0:00:00
Downloading typer-0.26.7-py3-none-any.whl (122 kB)
Downloading wasabi-1.1.3-py3-none-any.whl (27 kB)
Downloading weasel-1.0.0-py3-none-any.whl (50 kB)
Downloading cloudpathlib-0.24.0-py3-none-any.whl (63 kB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Installing collected packages: wasabi, spacy-loggers, spacy-legacy, shellingham, murmurhash, httpcore, cymem, confection, cloudpathlib, catalogue, blis, srsly, preshed, typer, thinc, httpx, weasel, spaCy

   ------ ---------------------------------  3/18 [shellingham]
   ----------------- ----------------------  8/18 [cloudpathlib]
   ---------------------- ----------------- 10/18 [blis]
   ------------------------ --------------- 11/18 [srsly]
   ------------------------ --------------- 11/18 [srsly]
   ---------------------------- ----------- 13/18 [typer]
   ------------------------------- -------- 14/18 [thinc]
   ------------------------------- -------- 14/18 [thinc]
   --------------------------------- ------ 15/18 [httpx]
   ------------------------------------- -- 17/18 [spaCy]
   ------------------------------------- -- 17/18 [spaCy]
   ------------------------------------- -- 17/18 [spaCy]
   ------------------------------------- -- 17/18 [spaCy]
   ------------------------------------- -- 17/18 [spaCy]
   ------------------------------------- -- 17/18 [spaCy]
   ------------------------------------- -- 17/18 [spaCy]
   ------------------------------------- -- 17/18 [spaCy]
   ------------------------------------- -- 17/18 [spaCy]
   ------------------------------------- -- 17/18 [spaCy]
   ------------------------------------- -- 17/18 [spaCy]
   ------------------------------------- -- 17/18 [spaCy]
   ------------------------------------- -- 17/18 [spaCy]
   ---------------------------------------- 18/18 [spaCy]

Successfully installed blis-1.3.3 catalogue-2.0.10 cloudpathlib-0.24.0 confection-1.3.3 cymem-2.0.13 httpcore-1.0.9 httpx-0.28.1 murmurhash-1.0.15 preshed-3.0.13 shellingham-1.5.4 spaCy-3.8.14 spacy-legacy-3.0.12 spacy-loggers-1.0.5 srsly-2.5.3 thinc-8.3.13 typer-0.26.7 wasabi-1.1.3 weasel-1.0.0
Note: you may need to restart the kernel to use updated packages.

In [47]:
import spacy

In [50]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     - -------------------------------------- 0.5/12.8 MB 5.6 MB/s eta 0:00:03
     ------------- -------------------------- 4.2/12.8 MB 15.7 MB/s eta 0:00:01
     ------------------------- -------------- 8.1/12.8 MB 18.0 MB/s eta 0:00:01
     --------------------------------------  12.6/12.8 MB 18.8 MB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 18.3 MB/s  0:00:00
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [51]:
nlp=spacy.load("en_core_web_sm")

In [52]:
doc=nlp("Apple is looking at buying U.K. startup for $1 billion")

In [53]:
doc.text

'Apple is looking at buying U.K. startup for $1 billion'

In [54]:
doc[1]

is

In [56]:
doc[2].pos_

'VERB'

In [57]:
doc[2].tag_

'VBG'

In [58]:
spacy.explain("VBG")

'verb, gerund or present participle'

In [59]:
for word in doc:
    print(word.text,"----->",word.pos_,word.tag_,spacy.explain(word.tag_))

Apple -----> PROPN NNP noun, proper singular
is -----> AUX VBZ verb, 3rd person singular present
looking -----> VERB VBG verb, gerund or present participle
at -----> ADP IN conjunction, subordinating or preposition
buying -----> VERB VBG verb, gerund or present participle
U.K. -----> PROPN NNP noun, proper singular
startup -----> VERB VBD verb, past tense
for -----> ADP IN conjunction, subordinating or preposition
$ -----> SYM $ symbol, currency
1 -----> NUM CD cardinal number
billion -----> NUM CD cardinal number

In [60]:
from spacy import displacy

In [61]:
displacy.render(doc,style="dep",jupyter=True)